<?php
require_once ("query_rcr_common.php");

define ("ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_TOTAL_FINAL_SCORE", "totalFinalScore");
define ("ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_MEAN_FINAL_SCORE", "meanFinalScore");
define ("ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_BEST_FINAL_SCORE", "bestFinalScore");
define ("ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_TOTAL_GAME_SCORE", "totalGameScore");
define ("ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_MEAN_GAME_SCORE", "meanGameScore");
define ("ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_BEST_GAME_SCORE", "bestGameScore");
define ("ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_WIN_RATE_4", "winRate4");
define ("ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_WIN_RATE_5", "winRate5");
define ("ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_POSITIVE_RATE_4", "positiveRate4");
define ("ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_POSITIVE_RATE_5", "positiveRate5");
define ("ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_TOTAL_FINAL_SCORE_ANNUAL", "totalFinalScoreAnnual");
define ("ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_TOTAL_FINAL_SCORE_TRIMENSTRIAL", "totalFinalScoreTrimestrial");
define ("ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_TOTAL_FINAL_SCORE_MENSUAL", "totalFinalScoreMensual");
define ("ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_TOTAL_GAME_SCORE_ANNUAL", "totalGameScoreAnnual");
define ("ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_TOTAL_GAME_SCORE_TRIMENSTRIAL", "totalGameScoreTrimestrial");
define ("ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_TOTAL_GAME_SCORE_MENSUAL", "totalGameScoreMensual");

define ("ACTION_GET_RCR_RANKING_PARAM_SORTING_MODE_HIGHEST", "highest");
define ("ACTION_GET_RCR_RANKING_PARAM_SORTING_MODE_LOWEREST", "lowest");
?>