<?php
require_once ("query_rcr_common.php");

define ("ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_TOTAL_FINAL_SCORE", "totalFinalScore");
define ("ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_MEAN_FINAL_SCORE", "meanFinalScore");
define ("ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_BEST_FINAL_SCORE", "bestFinalScore");
define ("ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_TOTAL_GAME_SCORE", "totalGameScore");
define ("ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_MEAN_GAME_SCORE", "meanGameScore");
define ("ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_BEST_GAME_SCORE", "bestGameScore");
define ("ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_WIN_RATE", "winRate");
define ("ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_POSITIVE_RATE", "positiveRate");
define ("ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_TOTAL_ANNUAL", "totalAnnual");
define ("ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_TOTAL_TRIMENSTRIAL", "totalTrimestrial");
define ("ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_TOTAL_MENSUAL", "totalMensual");

define ("ACTION_GET_RCR_RANKING_PARAM_SORTING_MODE_HIGHEST", "highest");
define ("ACTION_GET_RCR_RANKING_PARAM_SORTING_MODE_LOWEREST", "lowest");
?>