<?php
require_once ("query_rcr_common.php");

define ( "ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_TOTAL", "total" );
define ( "ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_FINAL_SCORE", "finalScore" );
define ( "ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_MEAN_FINAL_SCORE", "meanFinalScore" );
define ( "ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_GAME_SCORE", "gameScore" );
define ( "ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_MEAN_GAME_SCORE", "meanGameScore" );
define ( "ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_TOTAL_ANNUAL", "totalAnnual" );
define ( "ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_TOTAL_TRIMENSTRIAL", "totalTrimestrial" );
define ( "ACTION_GET_RCR_RANKING_PARAM_RANKING_MODE_TOTAL_MENSUAL", "totalMensual" );

define ( "ACTION_GET_RCR_RANKING_PARAM_SORTING_MODE_HIGHEST", "highest" );
define ( "ACTION_GET_RCR_RANKING_PARAM_SORTING_MODE_LOWEREST", "lowest" );

define ( "ACTION_GET_RCR_RANKING_PARAM_PERIOD_MODE_ALL", "all" );
define ( "ACTION_GET_RCR_RANKING_PARAM_PERIOD_MODE_YEAR", "year" );
define ( "ACTION_GET_RCR_RANKING_PARAM_PERIOD_MODE_TRIMESTER", "trimester" );
define ( "ACTION_GET_RCR_RANKING_PARAM_PERIOD_MODE_MONTH", "month" );
?>